name: PR2

joints:
  # TORSO
  torso_lift_joint:
    motor: torso_lift_joint
    sensor: torso_lift_joint_sensor

  # RIGHT ARM
  RShoulderYaw:
    motor: r_shoulder_pan_joint
    sensor: r_shoulder_pan_joint_sensor
  RShoulderPitch:
    motor: r_shoulder_lift_joint
    sensor: r_shoulder_lift_joint_sensor
  RShoulderRoll:
    motor: r_upper_arm_roll_joint
    sensor: r_upper_arm_roll_joint_sensor
  RElbowPitch:
    motor: r_elbow_flex_joint
    sensor: r_elbow_flex_joint_sensor
  RElbowYaw:
    motor: r_forearm_roll_joint
    sensor: r_forearm_roll_joint_sensor
  RWristPitch:
    motor: r_wrist_flex_joint
    sensor: r_wrist_flex_joint_sensor
  RWristRoll:
    motor: r_wrist_roll_joint
    sensor: r_wrist_roll_joint_sensor


