name: TIAGo
moveit_group: arm_torso
base_frame: base_footprint

chains:
  right:
    - arm_1_joint
    - arm_2_joint
    - arm_3_joint
    - arm_4_joint
    - arm_5_joint
    - arm_6_joint
    - arm_7_joint

joint_groups:
  right:
    shoulder:
      pitch: arm_1_joint
      roll: arm_2_joint
      yaw: arm_3_joint
    elbow:
      pitch: arm_4_joint
      yaw: arm_5_joint
    wrist:
      pitch: arm_6_joint
      roll: arm_7_joint
    gripper:
      finger1: gripper_left_finger_joint
      finger2: gripper_right_finger_joint


end_effectors:
  right: [torso_lift_link, gripper_tool_link]

grippers:
  right:
    joints: [gripper_left_finger_joint, gripper_right_finger_joint]
    open: 0.044
    closed: 0.0

default_orientation: [0.5, -0.5, -0.5, 0.5]
orientation_options:
  - [0.5, -0.5, -0.5, 0.5]
  - [0.0, -0.707, 0.0, 0.707]
  - [0.5, -0.5, 0.5, 0.5]
  - [0.5, -0.5, -0.5, -0.5]
