name: UR5e
moveit_group: arm
base_frame: base_link

chains:
  right:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint

joint_groups:
  right:
    shoulder:
      yaw: shoulder_pan_joint
      pitch: shoulder_lift_joint
    elbow:
      pitch: elbow_joint
    wrist:
      pitch: wrist_1_joint
      yaw: wrist_2_joint
      roll: wrist_3_joint
    gripper:
      finger1: finger_1_joint_1
      finger2: finger_2_joint_1
      finger3: finger_middle_joint_1

end_effectors:
  right: [base_link, tool0]

grippers:
  right:
    joints: [finger_1_joint_1, finger_2_joint_1, finger_middle_joint_1]
    open: 0.0495
    closed: 1.22

default_orientation: [0.0, 0.707, 0.0, 0.707]
orientation_options:
  - [0.0, 0.707, 0.0, 0.707]
  - [0.0, 0.0, 0.0, 1.0]
  - [0.5, 0.5, -0.5, 0.5]
